/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gravedigger_example_ra127_2014_com_taskmanager_NativeClass */

#ifndef _Included_gravedigger_example_ra127_2014_com_taskmanager_NativeClass
#define _Included_gravedigger_example_ra127_2014_com_taskmanager_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gravedigger_example_ra127_2014_com_taskmanager_NativeClass
 * Method:    izracunajProcente
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_gravedigger_example_ra127_12014_com_taskmanager_NativeClass_izracunajProcente
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
